version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5431'
  backend:
    image: ddd20098/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  frontend:
    image: ddd20098/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: ddd20098/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
